# Generated by Django 3.1.4 on 2020-12-30 01:04

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import gallery.models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2016), gallery.models.max_value_current_year])),
                ('medium', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Acrylic'), (2, 'Charcoal'), (3, 'Colored Pencil'), (4, 'Gouache'), (5, 'Graphite'), (6, 'Ink'), (7, 'Marker'), (8, 'Oil'), (9, 'Pastel'), (10, 'Pen'), (11, 'Watercolor')], max_length=23)),
                ('substrate', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Canvas'), (2, 'Linen'), (3, 'Panel'), (4, 'Paper')], max_length=7)),
                ('size', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images/')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
