# Generated by Django 3.1.4 on 2020-12-30 01:32

import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('gallery', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserFullName',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('auth.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AlterField(
            model_name='gallery',
            name='artist',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gallery.userfullname'),
        ),
    ]
