# Generated by Django 3.1.4 on 2020-12-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0002_auto_20201230_0132'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserFullName',
        ),
        migrations.AlterField(
            model_name='gallery',
            name='artist',
            field=models.CharField(default='Meredith Bakke', editable=False, max_length=20),
        ),
    ]
