# Generated by Django 3.1.5 on 2021-01-14 20:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('author', models.CharField(default='Meredith Bakke', max_length=200)),
                ('title', models.CharField(max_length=50)),
                ('year', models.IntegerField()),
                ('medium', models.CharField(max_length=50)),
                ('substrate', models.CharField(max_length=50)),
                ('size', models.CharField(max_length=20)),
                ('image', models.ImageField(blank=True, upload_to='artwork/')),
            ],
        ),
    ]
