# Generated by Django 3.1.4 on 2020-12-30 23:34

import django.core.validators
from django.db import migrations, models
import multiselectfield.db.fields
import posts.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist', models.CharField(default='Meredith Bakke', editable=False, max_length=20)),
                ('title', models.CharField(max_length=50)),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(2016), posts.models.max_value_current_year])),
                ('medium', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Acrylic'), (2, 'Charcoal'), (3, 'Colored Pencil'), (4, 'Gouache'), (5, 'Graphite'), (6, 'Ink'), (7, 'Marker'), (8, 'Oil'), (9, 'Pastel'), (10, 'Pen'), (11, 'Watercolor')], max_length=23)),
                ('substrate', multiselectfield.db.fields.MultiSelectField(choices=[(1, 'Canvas'), (2, 'Linen'), (3, 'Panel'), (4, 'Paper')], max_length=7)),
                ('size', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
